### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by matthew-brett** [craicrai/xrd_analysis_workflow#2]
I don't think the user needs to fork the repository - is that right?

You've mentioned `from .opencl import ocl` fix twice, in the main README list, and then at the end.  Maybe put in one place only?  It would be nice to have the explanation with the fix.  Or even a patch file to apply with `patch`.

**Comment by flaviu-gostin** [comment]
Great advice!  Thanks.
I did a patch.  Deleted redundant text in README.
